-- compute_forecast_history_window_and_median_cap.sql
--
-- Narrative doc, not a migration (nothing here touches the database schema
-- -- every change described is in the compute-forecast Edge Function itself,
-- index.ts / _shared/service_key.ts). Kept in docs/schema alongside the
-- other compute-forecast write-ups (EDGETEC_FORECAST_ROBUSTNESS_FIX_NOTES.md,
-- compute_forecast_reapply_and_flaky_zero_rows.sql) for the same reason
-- those exist: a forecast-quality bug found and fixed against real client
-- data deserves a permanent record of what was wrong and what changed, not
-- just a commit message.
--
-- 2026-09-30. Craig: "Have you run the Seasonal Forecast Calc Edge Function
-- across all clients earlier and has the Contribution by entity recalculated
-- accordingly? Doesn't seem right. Please check." Investigating that
-- surfaced three distinct, real bugs in compute-forecast's Holt-Winters
-- model -- all found and verified against live Morgenster 1711 (Pty) Ltd
-- data, all now fixed and deployed (compute-forecast version 7).
--
-- ============================================================================
-- Fix #4 -- unbounded history window
-- ============================================================================
-- `full_history_months` (forecast_settings, default 24) was always meant to
-- define "how much history counts as the full picture" -- the confidence-
-- tier check already used it that way -- but nothing ever actually bounded
-- the series fed into the model to that many months. A years-old anomalous
-- month sitting before a long dormant gap could still shape a forecast
-- computed today.
--
-- Real example: Morgenster sales rep *Z0100 traded normally in 2021
-- (including one real R629,500 month), went essentially quiet for ~4 years,
-- then resumed trading normally at R30k-80k/month in late 2025. That one
-- 2021 spike was still setting this rep's historical-max cap and shaping a
-- 2026 forecast.
--
--   Before: R5.46m/year forecast, vs. a real recent run-rate of ~R450k-950k.
--   After:  R776,543/year -- in line with real trading.
--
-- Fix: truncate the series to at most the most recent `full_history_months`
-- months before running Holt-Winters at all.
--
-- ============================================================================
-- Fix #5 -- peak-relative cap can't catch the peak itself
-- ============================================================================
-- The existing safeguard (2026-09-04/2026-09-21 fixes) capped the
-- deseasonalized value fed into the level/trend recursion at 1.5x the
-- entity's own highest actual month ever -- but that cap is built from the
-- very same number it's meant to guard against, so it can't help when the
-- entity's own historical maximum IS the anomaly.
--
-- Real example: Morgenster sales rep *R011 trades normally at
-- R35k-220k/month, but had two genuine, extreme one-off months (R802k in
-- Jun 2026, R589k in Nov 2024) that pulled its forecast well above its real
-- run-rate.
--
--   Before: R3.53m/year forecast, vs. a real run-rate of roughly R1-1.7m/
--           year (the two spike months make a clean "run-rate" figure
--           somewhat fuzzy -- see below).
--   After:  R2.59m/year -- down 27%, and defensible given a genuine R802k
--           sale landed as recently as Jun 2026 and legitimately raises
--           expectations; this is not a case that should go all the way to
--           R1m, just no longer 3.5x it.
--
-- Fix: the cap/floor is now the TIGHTER of the existing peak-relative bound
-- and a new bound relative to the entity's own MEDIAN non-zero month (5x,
-- MEDIAN_CAP_MULTIPLE in index.ts).
--
-- Control case verified unaffected by fixes 4 & 5: Morgenster sales rep
-- *113 -- continuous recent history, no dormant gap, no freak month --
-- forecasts R1,996,401/year, against a real recent run-rate of ~R1.56m/
-- year (23-month actuals, mv_sales_cube_monthly). Same order of magnitude
-- before and after; the model's normal trend/seasonality extrapolation
-- accounts for the rest, same as it always did.
--
-- ============================================================================
-- Fix #6 -- dormant entities still forecast off stale history
-- ============================================================================
-- Fixes 4 and 5 alone didn't close the gap this investigation actually set
-- out to check: summing every Morgenster sales rep's own forecast against
-- the Company dimension's own independently-computed forecast for the same
-- client and period.
--
--   Before any of today's fixes:  R40.5m (reps) vs. R15.9m (company) -- 2.55x
--   After fixes 4 & 5 only:       R39.6m (reps) vs. R21.7m (company) -- 1.82x
--   After fix 6 as well:          R27.9m (reps) vs. R21.7m (company) -- 1.29x
--
-- (The company-level figure itself moved between the second and third rows
-- because it hadn't been recomputed with fixes 4/5 live until the fix-6
-- verification pass -- R15.9m was the STALE pre-fix number in the first
-- comparison Craig originally flagged.)
--
-- Root cause, found by querying real sales data directly: 27 Morgenster
-- sales reps whose very LAST sale is 6+ months in the past -- several 2 to
-- 5+ years -- still had a live, often sizeable, forecast computed for
-- them: R12.1m combined, out of the R39.6m (fixes 4/5 only) total.
--
-- forecast_input_series() (003_wyzesales_forecast_series.sql) builds each
-- entity's series from its own first sale to its own LAST sale
-- (`end_month = max(month) from v_dimension_monthly_sales`) -- it does not
-- keep extending a dormant entity's series with trailing zero months all
-- the way through to today the way a currently-active entity's implicitly
-- does. So fix 4's "most recent full_history_months months" window, for a
-- rep who stopped trading 21 months ago, is 24 months of real but entirely
-- stale data -- nothing in the series itself distinguishes "active 21
-- months ago" from "active last month".
--
-- Real example: Morgenster sales rep *109's last-ever sale was December
-- 2024 -- 21 months before this fix. Its most-recent-24-months window (fix
-- 4) is built from real R100k-240k/month numbers from 2023-2024 that once
-- looked perfectly healthy.
--
--   Before fix 6: R2,760,121/year forecast, as if still an active rep.
--   After fix 6:  R0/year, confidence "low".
--
-- Other examples from the same 27-rep group (all last active 6+ months
-- ago, several years): *111 (36 months dormant, was R1.72m/year), *112 (32
-- months, was R1.47m/year), *101 (46 months, was R961k/year), *103 (65
-- months, was R589k/year) -- all now R0.
--
-- Fix: compute the gap between an entity's own last real month and today
-- BEFORE running Holt-Winters at all. When that gap is at least
-- `partial_history_months` (the SAME existing, client-configurable setting
-- already used to decide "is there enough recent history to trust a
-- seasonal pattern" -- reused here rather than inventing a new magic
-- number), forecast a flat zero instead of extrapolating a pattern with no
-- supporting evidence in over a year.
--
-- ============================================================================
-- Full-system verification (all clients, all dimensions, 2026-09-30)
-- ============================================================================
-- Re-ran every client_dimensions row (38 total across WCSA, Edgetec,
-- Fynbos, Morgenster) against the fixed function (version 7) -- all 38
-- returned HTTP 200 with no errors. Sum-of-entity-forecast vs.
-- Company-dimension-forecast, per client:
--
--   Fynbos Hill Vineyards:      R87.39m (reps) vs. R88.09m (company) -- 0.8% apart
--   Morgenster 1711 (Pty) Ltd:  R27.95m (reps) vs. R21.71m (company) -- 1.29x
--   Edgetec Systems (Pty) Ltd:  R109.57m (reps) vs. R153.72m (company) -- reps
--     are LOWER than company by ~29%, the opposite direction from
--     Morgenster's gap. Not investigated further as part of this fix -- it's
--     plausibly unattributed/house sales that land in the Company total but
--     don't attribute to any one rep (an "UNASSIGNED" branch code exists in
--     the raw sales cube), which is a normal, expected pattern rather than
--     a bug, but this wasn't confirmed against real Edgetec data the way
--     the Morgenster numbers above were. Worth a follow-up look if Craig
--     wants Edgetec's own Contribution-by-entity reviewed the same way.
--
-- Deployed as compute-forecast version 7 (Supabase project vnzflygyqslvlvndyhql).
-- Also fixed in the same version: a transcription bug introduced while
-- deploying fixes 4/5 (version 5) -- _shared/service_key.ts's legacy-key
-- fallback line was mistakenly typed as a second SUPABASE_SECRET_KEYS
-- lookup instead of the intended SUPABASE_SERVICE_ROLE_KEY fallback. Caught
-- and corrected before any dependent screen was affected (version 6, same
-- day), unrelated to fixes 4-6 above but shipped in the same investigation.

-- ============================================================================
-- Follow-up (same day) -- checking dormancy-zeroing (fix 6) across every
-- OTHER dimension, not just sales_person/company
-- ============================================================================
-- Craig: "Are you happy then that the daily Seasonal Forecast Edge Function
-- works correctly and apportions the Contribution by entity correctly etc?"
-- Answer at the time was "yes for sales_person/company, which is what was
-- actually spot-checked against real data; the other dimensions haven't
-- been deeply verified the same way." Craig: "Yes, please can you check the
-- other dimensions as well."
--
-- A first audit query against sales_forecast (join to each entity's real
-- last-activity month) appeared to find fix 6 failing for Morgenster's
-- dim_5/dim_6 (Range/Group) -- e.g. dim_6 entity "Olive - Buyers own brand
-- 118", genuinely dormant since Feb 2024 (31 months), still showing a live
-- ~R8.07m/year forecast. Traced this all the way through: confirmed the
-- deployed index.ts was exactly the intended fix-6 code (get_edge_function),
-- confirmed forecast_input_series() itself already correctly ends this
-- entity's series at Feb 2024 (checked directly with `set local role
-- service_role`), and confirmed a temporary debug build of this function
-- (console.log on the real fetch/group/dormancy-check path, invoked for
-- just this client+dimension) computed monthsSinceLastActivity=31 and
-- correctly wrote a flat R0/"low" forecast when run.
--
-- Root cause of the apparent discrepancy: NOT a code bug. The suspicious
-- R8.07m row's own computed_at was 2026-09-30 08:02:03 UTC -- BEFORE the
-- fix 4/5/6 deploy that same morning at 09:10:29 UTC. It was simply stale
-- data from the last pre-fix run of that specific dimension, not yet
-- recomputed under the fixed code. (Separately, a second false alarm in
-- the same audit turned out to be the audit query's own definition of
-- "last activity month" being stricter than forecast_input_series' real
-- one -- the audit only counted a month as "real activity" when its net
-- value was non-zero, while forecast_input_series/v_dimension_monthly_
-- sales counts any month with a real underlying transaction, including one
-- that net to R0 -- e.g. Morgenster item 22MSWH has a real, present
-- 2026-09-01 row worth R0.00. Under that stricter definition a handful of
-- items/customers looked "dormant" by a few months when they were not.)
--
-- Fix: none needed in index.ts -- fix 6 already worked correctly wherever
-- it had actually been re-run. Instead: (1) deployed a temporary debug
-- build (version 8) purely to log real fetch/pagination/grouping output
-- for the one flagged entity and confirm the above; (2) redeployed the
-- clean, unmodified fix-6 code as version 9 once confirmed (no functional
-- change from version 7 -- version 8 was debug-only and never meant to
-- stay live); (3) re-ran EVERY client_dimensions row (all 38, across WCSA/
-- Edgetec/Fynbos/Morgenster) through version 9 so every dimension's sales_
-- forecast rows are current, not just the ones already touched by earlier
-- verification passes; (4) re-ran the dormancy audit using forecast_input_
-- series' own exact "last real month, any value" definition instead of the
-- stricter one -- zero violations found, across every dimension of every
-- client.
--
-- Lesson for next time: after any compute-forecast deploy, a "looks wrong"
-- row found by querying sales_forecast directly needs its own computed_at
-- checked against the deploy's own updated_at before concluding the CODE
-- is wrong -- an unrecomputed dimension will keep showing pre-fix numbers
-- until it's re-run, which looks identical to a live regression unless you
-- check the timestamp.
